### ISSUE TITLE
Add script documentation

### ISSUE THREAD

**Issue by anoblet** [hyperpress/logicalphase#82]
In the readme there should be a section on install and repro. Even if it's just `npm i && polymer serve` :)

**Comment by anoblet** [comment]
Smooth on-boarding process. Installed polymer-cli globally and I was good to go. Thanks!

**Comment by hyperpress** [comment]
Thanks. I need to work up some useful docs for the projects. 😊

**Comment by hyperpress** [comment]
Straggler. Updated README.md to bring more up to date. Thanks
